name: check job

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: true
          fetch-depth: 2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

#      - name: Debug dependencies
#        run: |
#          pwd

      - name: Build dependencies
        run: npm run build

      - name: Test
        run: npm run test

      - name: Get diff from PR
        id: diff
        run: |
          git fetch origin
          git diff origin/master HEAD -- . ':!package-lock.json' ':!tsconfig.json' ':!dist/' > pr.diff

      - name: Set NODE_PATH
        run: export NODE_PATH=$PWD/node_modules

      - name: Run code review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pwd
          node ./review-helper.mjs < pr.diff > review_feedback.txt

      - name: Post review feedback as a comment
        env:
          GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
        run: |
          if [ -s review_feedback.txt ]; then
            REVIEW_FEEDBACK=$(cat review_feedback.txt)
            COMMENT_BODY=$(jq -n --arg body "$REVIEW_FEEDBACK" '{body: $body}')
            PULL_REQUEST_NUMBER=${{ github.event.pull_request.number }}
            curl -s -H "Authorization: token $GITHUB_TOKEN" -X POST -d "$COMMENT_BODY" \
              "https://api.github.com/repos/${{ github.repository }}/issues/$PULL_REQUEST_NUMBER/comments"
          else
            echo "No review feedback to post."
          fi

      - name: clean up
        run: |
          rm -rf node_modules
          rm -rf package-lock.json
          rm -rf dist
