name: check job

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: true
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build dependencies
        run: npm run build

      - name: Test
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
        continue-on-error: true

      - name: Clean up
        run: |
          rm -rf node_modules
          rm -rf package-lock.json
          rm -rf dist
